version: '3.3'

services:
  django:
    container_name: 'django_dsd'
    restart: always
    build:
      context: .
      dockerfile: ./DockerFile
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000
    depends_on: 
      - rabbitmq
  rabbitmq:
    container_name: 'rabbitmq_dsd'
    image: rabbitmq:3.7-alpine
    ports:
      - 5672:5672
  celery_flower:
    container_name: 'celery_flower_dsd'
    restart: always
    build:
      context: .
      dockerfile: ./DockerFile
    command: celery -A filas flower --port=5001
    ports:
      - 5001:5001
    volumes:
      - .:/code
    depends_on:
      - django
      - rabbitmq
  # celery_worker: 
  #   container_name: 'celery_worker_dsd'
  #   restart: always
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A tars worker -l info
  #   ports:
  #       - 6900:6900
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - django
  #     - rabbitmq