version: '3.3'

services:
  celery_worker: 
    container_name: 'celery_worker_dsd'
    environment:
      - DEBUG=${DEBUG}
    restart: always
    build: 
      context: .
      dockerfile: ./DockerFile
    command: celery -A filas worker -l info
    ports:
        - 6900:6900
    volumes:
      - .:/code
  celery_flower:
    container_name: 'celery_flower_dsd'
    restart: always
    build:
      context: .
      dockerfile: ./DockerFile
    command: celery -A filas flower --port=5001
    ports:
      - 5001:5001
    volumes:
      - .:/code