# Generated by Django 4.2.7 on 2023-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('task_status', models.CharField(max_length=50)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
