# Generated by Django 4.2.7 on 2023-11-24 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_workerinfo_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinfo',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerinfo',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
