# Generated by Django 4.2.7 on 2023-11-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workerinfo_creation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerinfo',
            old_name='request_host_external_ip_address',
            new_name='request_host_ip_address',
        ),
        migrations.RenameField(
            model_name='workerinfo',
            old_name='request_host_internal_ip_address',
            new_name='server_host_external_ip_address',
        ),
        migrations.RenameField(
            model_name='workerinfo',
            old_name='task_host_external_ip_address',
            new_name='server_host_internal_ip_address',
        ),
        migrations.RenameField(
            model_name='workerinfo',
            old_name='task_host_internal_ip_address',
            new_name='worker_host_external_ip_address',
        ),
        migrations.AddField(
            model_name='workerinfo',
            name='worker_host_internal_ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
